name: Check FLinks (Current Issue Only)

on:
  issues:
    types: [opened, edited]  # 仅在 Issue 创建或编辑时触发

jobs:
  check_links:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests PyGithub
          pip install -e .

      - name: Extract Issue Data
        id: extract-issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const issueNumber = context.payload.issue.number;
            core.exportVariable('ISSUE_BODY', issueBody);
            core.exportVariable('ISSUE_NUMBER', issueNumber);

      - name: Run Link Check (Current Issue)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python -m check_flinks.main  # 仅检测当前 Issue 的链接

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: link-status-report
          path: link_report.md

      - name: Auto Label Issue
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('./link_report.md', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });